config/routes.rb
Rails.application.routes.draw do
  resources :pens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pen.rb
class Pen < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pens_controller.rb
class PensController < ApplicationController
  before_action :set_pen, only: [:show, :edit, :update, :destroy]

  # GET /pens
  # GET /pens.json
  def index
    @pens = Pen.all
  end

  # GET /pens/1
  # GET /pens/1.json
  def show
  end

  # GET /pens/new
  def new
    @pen = Pen.new
  end

  # GET /pens/1/edit
  def edit
  end

  # POST /pens
  # POST /pens.json
  def create
    @pen = Pen.new(pen_params)

    respond_to do |format|
      if @pen.save
        format.html { redirect_to @pen, notice: 'Pen was successfully created.' }
        format.json { render :show, status: :created, location: @pen }
      else
        format.html { render :new }
        format.json { render json: @pen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pens/1
  # PATCH/PUT /pens/1.json
  def update
    respond_to do |format|
      if @pen.update(pen_params)
        format.html { redirect_to @pen, notice: 'Pen was successfully updated.' }
        format.json { render :show, status: :ok, location: @pen }
      else
        format.html { render :edit }
        format.json { render json: @pen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pens/1
  # DELETE /pens/1.json
  def destroy
    @pen.destroy
    respond_to do |format|
      format.html { redirect_to pens_url, notice: 'Pen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pen
      @pen = Pen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pen_params
      params.require(:pen).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pens_helper.rb
module PensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ok</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pens/_form.html.erb
<%= form_for(pen) do |f| %>
  <% if pen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pen.errors.count, "error") %> prohibited this pen from being saved:</h2>

      <ul>
      <% pen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pens/edit.html.erb
<h1>Editing Pen</h1>

<%= render 'form', pen: @pen %>

<%= link_to 'Show', @pen %> |
<%= link_to 'Back', pens_path %>

app/views/pens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pens</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pens.each do |pen| %>
      <tr>
        <td><%= pen.title %></td>
        <td><%= pen.description %></td>
        <td><%= link_to 'Show', pen %></td>
        <td><%= link_to 'Edit', edit_pen_path(pen) %></td>
        <td><%= link_to 'Destroy', pen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pen', new_pen_path %>

app/views/pens/new.html.erb
<h1>New Pen</h1>

<%= render 'form', pen: @pen %>

<%= link_to 'Back', pens_path %>

app/views/pens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pen.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pen.description %>
</p>

<%= link_to 'Edit', edit_pen_path(@pen) %> |
<%= link_to 'Back', pens_path %>